name: Deploy App
on: [workflow_dispatch]

jobs:
  deploy_to_heroku:
    name: Deploy To Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Push image to Heroku
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: welcome-image
          usedocker: true
          docker_heroku_process_type: web
